name: katalon Tests Suite Collection
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: "show wokspace path"
      run: echo '${{ github.workspace }}'
    - name: "show wokspace files"
      run: dir
    - name: Execute Test Suite Test
      uses: katalon-studio/katalon-studio-github-action@v4.0
      with:
         version: '9.6.0'
         projectPath: '${{ github.workspace }}'
         args: '-noSplash -retry=0 -browserType=Chrome -testSuiteCollectionPath="Test Suites/TS_RegressionTestCollection" -apiKey=  ${{ secrets.KATALON_API_KEY }}  --config -webui.autoUpdateDrivers=true'
         
