name: katalon Tests
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: log1
      run: echo "********************************************"      
    - name: "show github.workspace"
      run: echo '${{ github.workspace }}'
    - name: log3
      run: echo "********************************************"            
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v4.0
      with:
          version: '9.6.0'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -testSuiteCollectionPath="Test Suites/healthcare-tests - TS_RegressionTest" -apiKey= "294aa7c5-5a52-44cd-b64a-40994dd7e917" --config -webui.autoUpdateDrivers=true'
          
