name: katalon Tests Suite
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: "show wokspace path"
      run: echo '${{ github.workspace }}'
    - name: "show wokspace files"
      run: dir
    - name: Execute Test Suite Test
      uses: katalon-studio/katalon-studio-github-action@v4.0
      with:
         version: '10.0.1'
         projectPath: '${{ github.workspace }}'
         args: '-noSplash -retry=0 -browserType=Chrome -testSuitePath="Test Suites/TS_RegressionTest" -apiKey= "294aa7c5-5a52-44cd-b64a-40994dd7e917" --config -webui.autoUpdateDrivers=true'
         
